#!/usr/bin/env python3
"""Generate recently-added.json — a standalone "Recently Added" collection of
the N most recently added quotes across all collections.

"Recently added" cannot come from the data itself: quotes carry only quoteDate
(when the quote was *said*), and a collection's lastUpdated reflects its last
edit, not its creation. So recency is derived from git history:

  - For each collections/<id>.json, the commit that *created* the file defines
    that collection's initial batch of quotes. Those are excluded — they are
    "quotes from a newly added collection", not incremental additions.
  - A quote whose id first appears in a *later* commit was added to an
    already-existing collection. That commit's author date is its "added" date.

We then take the N newest such quotes (default 25), youngest first, and emit them
as a collection-shaped JSON file. This file is intentionally NOT registered in
collections.json and lives outside collections/: it reuses other collections'
quote ids/text, which would violate the one-prefix-per-collection and
cross-collection-uniqueness rules enforced by validate_collections.py.

Output is deterministic (lastUpdated = the newest included quote's added date),
so re-running with no new quotes produces no diff. Stdlib only.

Usage: build_recently_added.py [--root ROOT] [--limit N] [--out PATH]
"""

import argparse
import json
import os
import subprocess
import sys

# Presentation for the generated collection (new-palette color; see the token
# migration in scripts/migrate_colors.py).
META = {
    "id": "recently-added",
    "name": "Recently Added",
    "author": "Quips Editorial",
    "colorName": "sky",
    "colorLightHex": "#1F9ED4",
    "colorDarkHex": "#45C2FC",
    "iconName": "sparkles",
    "category": "Featured",
    "generated": True,
}


def git(root, *args):
    return subprocess.run(
        ["git", "-C", root, *args],
        capture_output=True, text=True, check=True,
    ).stdout


def quote_ids(blob):
    """Ids of the quotes in a raw collection-file blob (empty on any failure —
    e.g. a historical revision that didn't parse)."""
    try:
        data = json.loads(blob)
    except json.JSONDecodeError:
        return set()
    return {q.get("id") for q in data.get("quotes", []) if q.get("id")}


def added_events(root, rel_path):
    """Yield (quote_id, added_date_iso) for quotes added to rel_path *after* the
    file was created. Walks the file's commits oldest→newest, tracking the set of
    ids seen so far; the first commit seeds the set (initial batch, excluded)."""
    log = git(root, "log", "--reverse", "--format=%H|%aI", "--", rel_path).strip()
    if not log:
        return
    commits = [line.split("|", 1) for line in log.splitlines()]
    seen = set()
    for i, (sha, date) in enumerate(commits):
        ids = quote_ids(git(root, "show", f"{sha}:{rel_path}"))
        if i == 0:
            seen = ids                      # creation commit → initial batch
            continue
        for qid in ids - seen:              # ids new in this revision
            yield qid, date
        seen |= ids


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=".")
    ap.add_argument("--limit", type=int, default=25)
    ap.add_argument("--out", default=None, help="output path (default: <root>/recently-added.json)")
    args = ap.parse_args()

    coll_dir = os.path.join(args.root, "collections")
    files = sorted(fn for fn in os.listdir(coll_dir) if fn.endswith(".json"))

    # Current quote objects, keyed by id, plus their owning collection.
    current = {}
    for fn in files:
        cid = fn[:-5]
        data = json.load(open(os.path.join(coll_dir, fn), encoding="utf-8"))
        for q in data.get("quotes", []):
            if q.get("id"):
                current[q["id"]] = (cid, q)

    # Collect add-events across all files; keep only quotes that still exist.
    events = {}  # quote_id -> added_date (first time it was added post-creation)
    for fn in files:
        for qid, date in added_events(args.root, f"collections/{fn}"):
            if qid in current and qid not in events:
                events[qid] = date

    # Newest first; tie-break by id for stable ordering.
    ranked = sorted(events.items(), key=lambda kv: (kv[1], kv[0]), reverse=True)
    picked = ranked[: args.limit]

    quotes = []
    for qid, date in picked:
        cid, q = current[qid]
        quotes.append({**q, "sourceCollection": cid, "addedDate": date})

    newest = picked[0][1] if picked else None
    collection = {
        **META,
        "description": (
            f"The {len(quotes)} most recently added quotes across the Quips "
            "collections, excluding quotes introduced with brand-new collections. "
            "Generated by scripts/build_recently_added.py."
        ),
        "lastUpdated": newest or "",
        "quotes": quotes,
    }

    out = args.out or os.path.join(args.root, "recently-added.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(collection, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"wrote {len(quotes)} quote(s) to {out} (newest added {newest})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
